checkpoint: null
resume_trainer: True
model_overrides:
 sub_womd:
    _target_: hptr.utils.submission.SubWOMD
    activate: False
    method_name: ""  
    authors: [""]
    affiliation: ""
    description: ""
    method_link: ""
    account_name: ""
  sub_av2:
    _target_: hptr.utils.submission.SubAV2
    activate: True
